### PR TITLE
added neg binom fit

### PR DESCRIPTION
**Pull request by jgallowa07**
Added optional workflow for fitting a negative binomial as in https://matsengrp.github.io/phippery/bkg-model.html

### CODE REVIEW

**Comment by ksung25** [comment]
- Isolating the empirical samples seems unnecessary to me, because they aren't used anywhere. I suggest to remove [these lines](https://github.com/matsengrp/phip-flow/blob/a16964793bcf58aa8a99fb5841f520e2e61b70f7/bin/fit-predict-neg-binom.py#L43-L49)
- `modeling.neg_binom_model()` returns 3 objects when inplace is False: two lists containing the fit parameters per peptide ID and a copy of the xarray dataset. In the example, [this is all returned into one variable fit_ds](https://github.com/matsengrp/phip-flow/blob/a16964793bcf58aa8a99fb5841f520e2e61b70f7/bin/fit-predict-neg-binom.py#L53). Is this what you really want?
- I don't see where you issue a warning if the number of beads samples are low. Did you not put that in after all?

**Review by ksung25 — COMMENTED** [review]
- Isolating the empirical samples seems unnecessary to me, because they aren't used anywhere. I suggest to remove [these lines](https://github.com/matsengrp/phip-flow/blob/bdd7eb560123e482d2993ca4e32c365c85327037/bin/fit-predict-neg-binom.py#L43-L49)
- `modeling.neg_binom_model()` returns 3 objects when inplace is False: two lists containing the fit parameters per peptide ID and a copy of the xarray dataset. In the example, [this is all returned into one variable fit_ds](https://github.com/matsengrp/phip-flow/blob/bdd7eb560123e482d2993ca4e32c365c85327037/bin/fit-predict-neg-binom.py#L52). Is this what you really want?
- I don't see where you issue a warning if the number of beads samples are low. Did you not put that in after all?

**Comment by jgallowa07** [comment]
> Isolating the empirical samples seems unnecessary to me, because they aren't used anywhere. I suggest to remove these lines
good catch, should we be predicting on everything (even the sample that were fit on?)

> modeling.neg_binom_model() returns 3 objects when inplace is False: two lists containing the fit parameters per peptide ID and a copy of the xarray dataset. In the example, this is all returned into one variable fit_ds. Is this what you really want?

All I need to do is returned the xarray object, I guess. We could add more options to the pipeline that would allow us to return the parameter values, but let's put that off for the time being. 

> I don't see where you issue a warning if the number of beads samples are low. Did you not put that in after all?
added.

**Comment by ksung25** [comment]
> > Isolating the empirical samples seems unnecessary to me, because they aren't used anywhere. I suggest to remove these lines
> 
> good catch, should we be predicting on everything (even the sample that were fit on?)
> 
Computing p-values for input library samples is unnecessary. Having p-values for peptides counts in beads samples would allow us to perform some FDR-based method for establishing a p-value threshold (although I've seen that the beads samples sometimes have more extreme outliers than seen in empirical samples, thereby making the validity of using the beads samples in this way somewhat questionable...)

> > I don't see where you issue a warning if the number of beads samples are low. Did you not put that in after all?
> > added.
> 
> yup, added. Not sure there's a great way to do this other than a warning if there is less than say, 50 beads_only samples for the fit, and a pointer to the documentation.
>
Spotted some typos in the warning message. Here's the correction:
`"With less than 50 beads_only samples, it's probable that many peptide distribution fits will not converge, especially if coverage is low. See https://matsengrp.github.io/phippery/bkg-model.html for more."`

**Pull request closed without merging**
