### PR TITLE
Add beer

### PR DESCRIPTION
**Pull request by jgallowa07**
this PR:
*  Adds `params.run_edgrR_save_rds` default false to optionally run this workflow 
*  converts xarray phipdata to [PhIPData](https://www.bioconductor.org/packages/release/bioc/html/PhIPData.html) object
*  runs edge R
*  moves all "beer" references in code, and filenames to "edgeR"
*  exports a [PhIPData](https://www.bioconductor.org/packages/release/bioc/html/PhIPData.html) object with counts and edgeR hits using `saveRDS`

### CODE REVIEW

**Review by sminot — CHANGES_REQUESTED** [review]
Don't you think that we should also include the edgeR results in the CSV output in a way which can be accessed by the user?

I ran into Terry the other day, and she was actually quite interested in being able to look at the edgeR results for their current datasets. 

Since we're running edgeR anyway, it seems like it would be worth exposing those as tabular outputs.

**Comment by jgallowa07** [comment]
Great point, I agree. I should be able to get to this tomorrow or Thursday.

**Comment by jgallowa07** [comment]
Alright, @sminot, I've merged the three edgeR "assay's" i.e. edgeR_pval, edgeR_logfc, and edgeR_hits back into the xarray object that is passed back to the DSOUT workflow so now all the edge R results get written alongside the rest of the outputs (i.e. tall, wide, pickle). So when I run:
```
nextflow run main.nf \
  --sample_table data/pan-cov-example-with-beads-no-lib/sample_table.csv \
  --peptide_table data/pan-cov-example-with-beads-no-lib/peptide_table.csv \
  -profile docker -with-report $(date -I)-beer.html \
  --output_tall_csv true \
  --output_wide_csv true \
  --run_edgeR_save_rds true \
  --results $(date -I)-test -resume
```
I get the following wide results
```
(base) ubuntu phippery/phip-flow ‹add_beer*› » tree 2023-06-05-test/wide_data 
2023-06-05-test/wide_data
├── data_counts.csv
├── data_cpm.csv
├── data_edgeR_hits.csv
├── data_edgeR_logfc.csv
├── data_edgeR_logpval.csv
├── data_peptide_annotation_table.csv
├── data_sample_annotation_table.csv
└── data_size_factors.csv

0 directories, 8 files
```
How does this look?

**Comment by jgallowa07** [comment]
I still think it's worth throwing a useful error/warning if the dataset has less than 2 "beads_only" control. What are your thoughts? I'm not sure what the best way to do this is tbh.

**Comment by sminot** [comment]
> I still think it's worth throwing a useful error/warning if the dataset has less than 2 "beads_only" control. What are your thoughts? I'm not sure what the best way to do this is tbh.

I find it best to do this in the sample table validation step: see e9ba394

**Comment by sminot** [comment]
Is it weird that we're running edgeR by loading the `beer` library?

**Review by sminot — APPROVED** [review]
Ran test data through using edgeR with no problems

**Pull request merged**
